### ISSUE TITLE
Found a new bug in Junit Complexfunction

### ISSUE THREAD

**Issue by AviChickvashvili** [VadimKachevski/OOP_Ex1#1]
Hello comrade , 
found new bug while 
ComplexFunction x1 = new ComplexFunction("plus", m1,m2);
		x1.mul(x1);
		x1.div(x1);
		x1.comp(x1);
		x1.plus(x1);
		System.out.println(x1);
		function y = new ComplexFunction(x1.initFromString(x1.toString()));
		System.out.println(y);
		assertEquals(x1, y);

x and y should be equals but 
x is : plus(comp(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),div(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3)))),comp(comp(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),div(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3)))),div(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3)))))
and y is : none(plus(comp(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),div(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3)))),comp(comp(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),div(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3)))),div(div(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))),mul(mul(plus(2.0x^2,3.0x^3),plus(plus(2.0x^2,3.0x^3),3.0x^3)),plus(plus(2.0x^2,3.0x^3),3.0x^3))))))
as you can see 
y got a spare none operation in the start

**Comment by VadimKachevski** [comment]
change to to FIX:
function y = new ComplexFunction(x1.initFromString(x1.toString()).toString());

the constructor added None because only left function was sent.
