### ISSUE TITLE
new bug - Junit complexfunction - equalsTest

### ISSUE THREAD

**Issue by AviChickvashvili** [VadimKachevski/OOP_Ex1#3]
Hello , 
there is a bug with equals test.
while checking if complexfunction is equls to monom return true;
the check monom equals to complexfunction return false;

Monom test = new Monom("0");
function left = new Monom("0");
ComplexFunction p3 = new ComplexFunction(left) ;

**Comment by VadimKachevski** [comment]
Fixed bug. in complex function.
